Make it so we don't require the [err]common.sh files for install_part2

diff --git a/install_part2 b/install_part2
--- a/install_part2
+++ b/install_part2
@@ -15,10 +15,10 @@
 # License: GPLv2
 name=$(basename $0)
 PFX=$(dirname $(which $0))
-source ${PFX}/common.sh || {
- echo "${name}: fatal: could not source ${PFX}/common.sh , aborting..."
- [ "${parent}" = "bash" ] && exit 1 || return 1
-} |tee -a ${LOGFILE_COMMON}
+#source ${PFX}/common.sh || {
+# echo "${name}: fatal: could not source ${PFX}/common.sh , aborting..."
+# [ "${parent}" = "bash" ] && exit 1 || return 1
+#} |tee -a ${LOGFILE_COMMON}
 source ${PFX}/cquats_common.sh || {
  echo "${name}: fatal: could not source ${PFX}/cquats_common.sh , aborting..."
  [ "${parent}" = "bash" ] && exit 1 || return 1
@@ -41,13 +41,13 @@ To run CQuATS, do:
 #[ -f ${INSTDIR}/.first ] && {
 
 [ -d ${LOCAL_INSTDIR} ] && {
-becho "CQuATS :: Local Install (for user ${LOGNAME}) is already done ...
+echo "CQuATS :: Local Install (for user ${LOGNAME}) is already done ...
 ${RUN_MSG_HOWTO}"
   exit 1
 }
 
 {
-  becho "[+] CQuATS :: First run detected, setting up Local Install for user ${LOGNAME} now ..."
+  echo "[+] CQuATS :: First run detected, setting up Local Install for user ${LOGNAME} now ..."
   mkdir -p ${LOCAL_INSTDIR} ${gCQUATS_SCRATCH_FOLDER} 2>/dev/null
 
   cp -a ${INSTDIR}/* ${LOCAL_INSTDIR}/
@@ -55,20 +55,20 @@ ${RUN_MSG_HOWTO}"
  # doesn't just work with the soft links..
  #  ln -sf ${LOCAL_INSTDIR}/menuconfig
  #  ln -sf ${LOCAL_INSTDIR}/run_cquats
-  becho "Done.
+  echo "Done.
 ${RUN_MSG_HOWTO}"
   exit 0
 } |tee -a ${LOGFILE_COMMON}
 
 exit 0
 
-#[ -f ${INSTDIR}/.first ] && {
-  cd ${MENUDIR} || exit 1
-  #cd kbuild || exit 1
-  # mconf is the binary executable used for the 'menuconfig' target
-  make distclean   #mrproper
-  rm -f scripts/kconfig/mconf ../.first
-#} |tee -a ${LOGFILE_COMMON}
+##[ -f ${INSTDIR}/.first ] && {
+#  cd ${MENUDIR} || exit 1
+#  #cd kbuild || exit 1
+#  # mconf is the binary executable used for the 'menuconfig' target
+#  make distclean   #mrproper
+#  rm -f scripts/kconfig/mconf ../.first
+##} |tee -a ${LOGFILE_COMMON}
 #########
 
-exit 0
+#exit 0
