Adjust the system install script; tell user & get confirmation on first run

diff --git a/install_system b/install_system
--- a/install_system
+++ b/install_system
@@ -12,9 +12,12 @@
 name=$(basename $0)
 INSTDIR=/usr/share/cquats
 INST_DIRS=(kbuild tools)
-INST_FILES=(color.sh cquats_common.sh menuconfig README.md common.sh \
+INST_FILES=(install_system color.sh cquats_common.sh menuconfig README.md common.sh \
 err_common.sh LICENSE README_dev run_cquats)
-LOCAL_FILES_DELETE=(menuconfig run_cquats color.sh common.sh err_common.sh)
+
+runMsg="Run CQuATS (as a regular user, not root) ::
+ ${INSTDIR}/menuconfig
+ ${INSTDIR}/run_cquats"
 
 [ $(id -u) -ne 0 ] && {
   echo "${name}: need root access to install CQuATS."
@@ -27,20 +30,21 @@ LOCAL_FILES_DELETE=(menuconfig run_cquats color.sh common.sh err_common.sh)
   [FYI, over here: ${INSTDIR} ]
   Aborting install...
   
-  Try running the install_local program to install CQuATS for you locally,\
- as a regular user, not root."
+${runMsg}"
   exit 1
 }
 
-echo "CQuATS Installation Part 1 - System Install - proceeding ..."
-mkdir -p ${INSTDIR}
+echo "CQuATS System Installation proceeding ..."
+mkdir -p ${INSTDIR} || exit 1
 
 # Copy files across
-for afile in "install_system install_local ${INST_FILES[@]}"
+for afile in "${INST_FILES[@]}"
 do
   printf "%20s --> %s\n" ${afile} ${INSTDIR}
   cp -u ${afile} ${INSTDIR} || {
-    echo "${name}: cp failed [status=$?], aborting..." ; exit 1
+    echo "${name}: cp failed [status=$?], rolling back the install and aborting..."
+	rm -rf ${INSTDIR}
+	exit 1
   }
 done
 
@@ -49,13 +53,15 @@ for afolder in "${INST_DIRS[@]}"
 do
   printf "%20s/ --> %s\n" ${afolder} ${INSTDIR}
   cp -au ${afolder} ${INSTDIR}/ || {
-    echo "${name}: cp failed [status=$?], aborting..." ; exit 1
+    echo "${name}: cp failed [status=$?], rolling back the install and aborting..."
+	rm -rf ${INSTDIR}
+	exit 1
   }
 done
 chown -R root:root ${INSTDIR}
 
-# Now delete the src files from here, the 'local' folder..
-for afile in "${LOCAL_FILES_DELETE[@]}"
+# Now delete the src files from here, the 'temp download' folder..
+for afile in "${INST_FILES[@]}"
 do
   rm -f ${afile}
 done
@@ -68,8 +74,8 @@ done
 #echo "${name}: install dir: ${INSTDIR}"
 #ls -l ${INSTDIR}
 
-echo "${name}: CQuATS System Installation Part 1 successful.
+echo "
+${name}: CQuATS System Installation successful.
 
-Now pl run the install_local program, as a regular user (not root), \
-to install CQuATS locally for you."
+${runMsg}"
 exit 0
diff --git a/menuconfig b/menuconfig
--- a/menuconfig
+++ b/menuconfig
@@ -10,8 +10,8 @@
 #  https://github.com/masahir0y/kbuild_skeleton
 # All credit to the original devs.
 #
-# Last Updated :
-# Created      : 20Sep2017
+# Last Updated : 15Nov2017
+# Created      : 14Nov2017
 # License: GPLv2
 name=$(basename $0)
 PFX=$(dirname $(which $0))
@@ -28,15 +28,26 @@ source ${PFX}/cquats_common.sh || {
 #pwd
 
 ###
-### We ASSUME that CQuATS is now installed in ~/<wherever>/.cquats
+### We ASSUME that CQuATS is now installed in ${INSTDIR}/
 ### and is ready to run.
-### Implies that this script is now copied into the local location too...
 ###
 
 ### First local run
-#[ -f ${LOCAL_INSTDIR}/.first ] && {
 [ ! -d ${gCQUATS_SCRATCH_FOLDER} ] && {
   echo "[+] ${gPRJ} :: first-time-run detected :: mode: ${MODE}"
+  echo "
+Note: this folder - $(pwd) - will
+become your CQuATS Workspace. 
+ (Of course, you are free to setup multiple CQuATS workspaces by running this
+  program from different folders).
+
+Proceed? [y/N]
+"
+  read re
+  [ "${re}" != "y" -a "${re}" != "Y" ] && {
+    echo "CQuATS now aborting.."
+	exit 1
+  }
   mkdir -p ${gCQUATS_SCRATCH_FOLDER} #2>/dev/null
 
 [ 0 -eq 1 ] && {
