Cleanup the kbuild/ system; invoke the check_deps() func from the menuconfig script as well..

diff --git a/menuconfig b/menuconfig
--- a/menuconfig
+++ b/menuconfig
@@ -15,17 +15,25 @@
 # License: GPLv2
 name=$(basename $0)
 PFX=$(dirname `which $0`)
+source ${PFX}/common.sh || {
+ echo "${name}: fatal: could not source ${PFX}/common.sh , aborting..."
+ [ "${parent}" = "bash" ] && exit 1 || return 1
+}
 source ${PFX}/cquats_common.sh || {
  echo "${name}: fatal: could not source ${PFX}/cquats_common.sh , aborting..."
  [ "${parent}" = "bash" ] && exit 1 || return 1
-}
+} |tee -a ${LOGFILE_COMMON}
+
+{
+check_deps "make"  #perf spatch xterm"
 
 cd ${MENUDIR}
 echo "${gPRJ}:${name}: menu system loading, pl wait ..."
 #progress_wheel &
 #progpid=$!
+} |tee -a ${LOGFILE_COMMON}
 
-make menuconfig
+make menuconfig 2>> ${LOGFILE_COMMON}
  # latest choices are in it's .config
 #kill ${progpid} >/dev/null 2>&1
 exit 0
