perf record & report: user can now set the perf report folder location

diff --git a/run_cquats b/run_cquats
--- a/run_cquats
+++ b/run_cquats
@@ -435,7 +435,9 @@ if [ $? -eq 0 ] ; then   # this 'if' Must immd follow the check_if_config_foo_se
 		local perf_report_opts=$(echo "${tmp}" |tr '\n' '\0' 2>/dev/null)
 		tmp=$(check_config_foo_get_retval CONFIG_PERF_REPORT_FILE)
 		local perf_report_file=$(echo "${tmp}" |tr '\n' '\0' 2>/dev/null)
-		local perf_report_path=${gCQUATS_REPORTS_FOLDER}/${perf_report_file}
+		#local perf_report_path=${gCQUATS_REPORTS_FOLDER}/${perf_report_file}
+		tmp=$(check_config_foo_get_retval CONFIG_PERF_REPORT_FOLDER)
+		local perf_report_folder=$(echo "${tmp}" |tr '\n' '\0' 2>/dev/null)
 
 		perf_check_proc_settings
 
@@ -465,12 +467,30 @@ do
   }
 done
 
-echo "[+] running perf record on target app PID \${tpid} now"
+# Setup 'reports/result' folder etc
+# .-reports
+#     |-perf_on_<app-name>
+#         <perf.data-out-file>, \$SVG
+SVG=flamegraph.svg
+#PDIR=${gCQUATS_REPORTS_FOLDER}/perf_on_$(basename ${perf_target_app})_$(date +%d%b%Y_%H%M)
+PDIR=${perf_report_folder}/perf_on_$(basename ${perf_target_app})_$(date +%d%b%Y_%H%M)
+#echo "PDIR = ${PDIR} SVG=${SVG}"
+mkdir -p \${PDIR} || {
+  echo "CQuATS :: perf internal script: ERROR: creating report folder.
+Recheck that permission is okay and/or reset via 'menuconfig', and retry"
+  exit 1
+}
+chown -R \${LOGNAME}:\${LOGNAME} ${gCQUATS_REPORTS_FOLDER}
+cd \${PDIR}
+
+echo "[+] running perf record on target app PID \${tpid} now
+ [Output: ${perf_record_file}]"
 perf record -p \${tpid} ${perf_record_opts} --output=${perf_record_file}
 sleep 1
-echo "[+] writing perf report now into ${perf_report_path}"
-perf report ${perf_report_opts} --input=${perf_record_file} > ${perf_report_path} 2>&1
-ls -lh ${perf_report_path}
+#perf_report_path=\${PDIR}/perf_report.txt
+echo "[+] writing perf report now into \${PDIR}/perf_report.txt"
+perf report ${perf_report_opts} --input=${perf_record_file} > perf_report.txt 2>&1
+ls -lh perf_report.txt
 exit 0
 # end
 @EOF@
