For the perf record/report profiling tool, add capability to generate a "flamegraph"

diff --git a/run_cquats b/run_cquats
--- a/run_cquats
+++ b/run_cquats
@@ -435,9 +435,10 @@ if [ $? -eq 0 ] ; then   # this 'if' Must immd follow the check_if_config_foo_se
 		local perf_report_opts=$(echo "${tmp}" |tr '\n' '\0' 2>/dev/null)
 		tmp=$(check_config_foo_get_retval CONFIG_PERF_REPORT_FILE)
 		local perf_report_file=$(echo "${tmp}" |tr '\n' '\0' 2>/dev/null)
-		#local perf_report_path=${gCQUATS_REPORTS_FOLDER}/${perf_report_file}
 		tmp=$(check_config_foo_get_retval CONFIG_PERF_REPORT_FOLDER)
 		local perf_report_folder=$(echo "${tmp}" |tr '\n' '\0' 2>/dev/null)
+		tmp=$(check_config_foo_get_retval CONFIG_PERF_FLAME_GRAPH)
+		local perf_flamegraph=$(echo "${tmp}" |tr '\n' '\0' 2>/dev/null)
 
 		perf_check_proc_settings
 
@@ -447,21 +448,41 @@ if [ $? -eq 0 ] ; then   # this 'if' Must immd follow the check_if_config_foo_se
 local perfrun=${gCQUATS_SCRATCH_FOLDER}/.cquats.perf.sh
 cat > ${perfrun} << @EOF@
 #!/bin/bash
+# This script is part of the CQuATS project; it's dynamically generated by
+# the CQuATS runtime.
 # CQuATS - temp perf record & report script
+
+gen_flamegraph_svg()
+{
+echo "
+[+] ${name}: perf flame graph: working ... generating SVG file \"\${SVG}\" now..."
+perf script --input ${perf_record_file} |${TOOLS_PERF_FLMGR}/stackcollapse-perf.pl \
+   |${TOOLS_PERF_FLMGR}/flamegraph.pl > \${SVG} || {
+  echo "${name}:gen_flamegraph_svg() failed."
+  exit 1
+}
+ls -lh ${SVG}
+echo "View the above SVG file in your web browser to see the Flame Graph."
+} # end func gen_flamegraph_svg()
+
+### 'main'
 echo "[+] ${name}: userland|profiling|-|perf:${perfrun}"
 echo "[+]  running perf target app \"${perf_target_app}\" now within xterm"
 xterm -e ${perf_target_app} &
 sleep 0.5
 
-i=1
+i=1 ; max=5
 while [ true ]
 do
-  tpid=\$(pidof -s $(basename ${perf_target_app}))
+  export tpid=\$(pidof -s $(basename ${perf_target_app}))
     # pidof -s :Single shot - this instructs the program to only return one pid
-  [ ! -z "\${tpid}" ] && break
+  [ ! -z "\${tpid}" ] && {
+    echo "      <fyi, got PID \${tpid} in \$i/\${max} try|ies>"
+    break
+  }
   sleep 0.5
   let i=i+1
-  [ \$i -gt 5 ] && {
+  [ \$i -gt \${max} ] && {
     echo "[!]  Whoops, could NOT get process pid, aborting perf record run.."
     exit 1
   }
@@ -471,26 +492,25 @@ done
 # .-reports
 #     |-perf_on_<app-name>
 #         <perf.data-out-file>, \$SVG
-SVG=flamegraph.svg
-#PDIR=${gCQUATS_REPORTS_FOLDER}/perf_on_$(basename ${perf_target_app})_$(date +%d%b%Y_%H%M)
-PDIR=${perf_report_folder}/perf_on_$(basename ${perf_target_app})_$(date +%d%b%Y_%H%M)
-#echo "PDIR = ${PDIR} SVG=${SVG}"
+export PDIR=${perf_report_folder}/perf_on_$(basename ${perf_target_app})_$(date +%d%b%Y_%H%M)
 mkdir -p \${PDIR} || {
-  echo "CQuATS :: perf internal script: ERROR: creating report folder.
+  echo "[!] CQuATS :: perf internal script: ERROR: creating report folder.
 Recheck that permission is okay and/or reset via 'menuconfig', and retry"
   exit 1
 }
-chown -R \${LOGNAME}:\${LOGNAME} ${gCQUATS_REPORTS_FOLDER}
+export SVG=\${PDIR}/flamegraph_$(basename ${perf_target_app}).svg
+echo "PDIR = \${PDIR} SVG=\${SVG}"
+chown -R \${LOGNAME}:\${LOGNAME} ${perf_report_folder}
 cd \${PDIR}
 
 echo "[+] running perf record on target app PID \${tpid} now
  [Output: ${perf_record_file}]"
 perf record -p \${tpid} ${perf_record_opts} --output=${perf_record_file}
 sleep 1
-#perf_report_path=\${PDIR}/perf_report.txt
 echo "[+] writing perf report now into \${PDIR}/perf_report.txt"
 perf report ${perf_report_opts} --input=${perf_record_file} > perf_report.txt 2>&1
 ls -lh perf_report.txt
+[ "${perf_flamegraph}" = "y" ] && gen_flamegraph_svg
 exit 0
 # end
 @EOF@
