refactor so first-time works correctly; also, don't write into logfile (as the 'menuconfig' causes extraneous chars to flow in)

diff --git a/src/menuconfig b/src/menuconfig
--- a/src/menuconfig
+++ b/src/menuconfig
@@ -32,37 +32,7 @@ source ${PFX}/cquats_common.sh || {
 ### and is ready to run.
 ###
 
-### First local run
-[ ! -d ${gCQUATS_SCRATCH_FOLDER} ] && {
-  echo "[+] ${gPRJ} :: first-time-run detected :: mode: ${MODE}"
-  echo "
-Note: this folder - $(pwd) - will
-become your CQuATS Workspace. 
- (Of course, you are free to setup multiple CQuATS workspaces by running this
-  program from different folders).
-
-Proceed? [y/N]
-"
-  read re
-  [ "${re}" != "y" -a "${re}" != "Y" ] && {
-    echo "CQuATS now aborting.."
-	exit 1
-  }
-  mkdir -p ${gCQUATS_SCRATCH_FOLDER} #2>/dev/null
-
-[ 0 -eq 1 ] && {
-  cd ${MENUDIR} || exit 1
-  #cd kbuild || exit 1
-  # mconf is the binary executable used for the 'menuconfig' target
-  rm -f ${MENUDIR}/.config*
-  make distclean   #mrproper
-  rm -f scripts/kconfig/mconf #../.first
-}
-} |tee -a ${LOGFILE_COMMON}
-#########
-
-
-### NOT the first local run
+not_first_time()
 {
 check_deps "gcc make"  #perf spatch xterm"
 
@@ -73,6 +43,40 @@ echo "${gPRJ}:${name}: menu system loading, pl wait ..."
 # file generated by kbuild/Makefile; this way, we get 'multiuser' support;
 # each user can generate his private .config in his 'cquats' workspace!
 UCONFDIR=${LOCAL_INSTDIR} make menuconfig
-} #|tee -a ${LOGFILE_COMMON}
+}
 
+### "main" here
+
+### First local run?
+if [ ! -d ${gCQUATS_SCRATCH_FOLDER} ] ; then
+  echo "[+] ${gPRJ} :: first-time-run detected :: mode: ${MODE}"
+  echo "
+Note: this folder - $(pwd) - will
+become your CQuATS Workspace. 
+ (Of course, you are free to setup multiple CQuATS workspaces by running this
+  program from different folders).
+
+Proceed? [y/N] "
+  read re
+  [ "${re}" != "y" -a "${re}" != "Y" ] && {
+    echo "CQuATS now aborting.."
+	exit 1
+  }
+  mkdir -p ${gCQUATS_SCRATCH_FOLDER} #2>/dev/null
+  not_first_time
+
+ [ 0 -eq 1 ] && {
+  cd ${MENUDIR} || exit 1
+  #cd kbuild || exit 1
+  # mconf is the binary executable used for the 'menuconfig' target
+  rm -f ${MENUDIR}/.config*
+  make distclean   #mrproper
+  rm -f scripts/kconfig/mconf #../.first
+ }
+
+else   ### NOT the first local run
+
+ not_first_time
+
+fi #|tee -a ${LOGFILE_COMMON}
 exit 0
